version: "3.9"

services:
  # ================== POSTGRES ==================
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: range_wave
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # ================== REDIS ==================
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  # ================== RABBITMQ ==================
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - app-network

  # ================== NODE APP ==================
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node_app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - app-network

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:

networks:
  app-network:
    driver: bridge
